#!/usr/bin/env bash
set -euo pipefail
BASE_NS="${BASE_NS:-mysterns}"; VETH_PREFIX="${VETH_PREFIX:-myster}"; WORKDIR="${WORKDIR:-/tmp/mysterium_multi}"; MYST_BASE_DIR="${MYST_BASE_DIR:-./myst}"; MYST_BIN="${MYST_BIN:-myst}"; MYST_UI_BASE_PORT="${MYST_UI_BASE_PORT:-4449}"; mkdir -p "$WORKDIR" "$MYST_BASE_DIR"
source "$(cd "$(dirname "$0")" && pwd)/expressvpn_common.sh"
require_root(){ [[ $EUID -eq 0 ]] || exit 1; command -v "$MYST_BIN" >/dev/null 2>&1 || { echo "myst missing"; exit 1; }; command -v socat >/dev/null 2>&1 || { echo "socat missing"; exit 1; }; }
setup_nat_once(){ sysctl -w net.ipv4.ip_forward=1 >/dev/null; iptables -t nat -C POSTROUTING -s 10.0.0.0/8 -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s 10.0.0.0/8 -j MASQUERADE; }
calc_octets(){ local i="$1"; echo $(( (i-1)/254+1 )) $(( (i-1)%254+1 )); }
create_ns(){ local i="$1" ns="${BASE_NS}${i}" vh="${VETH_PREFIX}${i}h" vn="${VETH_PREFIX}${i}n" b c; read -r b c <<<"$(calc_octets "$i")"; ip netns add "$ns" 2>/dev/null || true; ip link show "$vh" >/dev/null 2>&1 || ip link add "$vh" type veth peer name "$vn"; ip link set "$vn" netns "$ns"; ip addr add "10.${b}.${c}.1/24" dev "$vh" 2>/dev/null || true; ip link set "$vh" up; ip netns exec "$ns" ip addr add "10.${b}.${c}.2/24" dev "$vn" 2>/dev/null || true; ip netns exec "$ns" ip link set lo up; ip netns exec "$ns" ip link set "$vn" up; ip netns exec "$ns" ip route replace default via "10.${b}.${c}.1" dev "$vn"; echo "$ns"; }
start_fwd(){ local i="$1" ns="$2" hp=$((MYST_UI_BASE_PORT+i)); socat "TCP-LISTEN:${hp},bind=127.0.0.1,reuseaddr,fork" "EXEC:ip netns exec ${ns} socat STDIO TCP\:127.0.0.1\:${MYST_UI_BASE_PORT},nofork" >"$WORKDIR/fwd_$i.log" 2>&1 & echo $! > "$WORKDIR/fwd_$i.pid"; }
cleanup(){ for f in "$WORKDIR"/*.pid; do [[ -f "$f" ]] && kill "$(cat "$f")" 2>/dev/null || true; done; for i in $(seq 1 "${INSTANCE_COUNT:-0}"); do ip netns del "${BASE_NS}${i}" 2>/dev/null || true; ip link del "${VETH_PREFIX}${i}h" 2>/dev/null || true; done; }
trap cleanup EXIT
main(){ require_root; ensure_expressvpn_binaries; setup_nat_once; prompt_vpn_settings; for i in $(seq 1 "$INSTANCE_COUNT"); do ns="$(create_ns "$i")"; start_expressvpn_in_ns "$ns" "$i" "${SELECTED_REGIONS[$((i-1))]}" "$WORKDIR"; root="$MYST_BASE_DIR/myst-$i"; mkdir -p "$root/data" "$root/config" "$root/run" "$root/script" "$root/logs"; start_fwd "$i" "$ns"; ip netns exec "$ns" bash -lc "exec '$MYST_BIN' --data-dir='$root/data' --config-dir='$root/config' --runtime-dir='$root/run' --script-dir='$root/script' service --agreed-terms-and-conditions" >"$root/logs/myst.log" 2>&1 & echo $! > "$WORKDIR/myst_$i.pid"; done; wait; }
main "$@"
